94 authentification registration - tests
SE-TINF22B2/G2-Schoolify pull request #194
Opened 2024-03-16 13:22 UTC by tilwbr

### Beschreibung der Änderungen
- added tests for post request to create student

### Issue
- #94 
### Checklist

- [x] Ich habe meinen code selber überprüft
- [x] Das Projekt kann ohne Probleme gestartet werden
- [x] Ich habe Tests geschrieben, falls das Issue ein Core Feature ist.
- [x] Ich habe meine Funktionen für die Verständlichkeit anderer mit Kommentaren ausgestattet
- [x] Ich habe den code gelinted (´npm run lint´)

2024-03-16 13:23 UTC, tilwbr commented
gitignore ist für vscode configuration :)

2024-03-18 07:51 UTC, CodeRider101 approved these changes

2024-03-18 10:57 UTC, CodeRider101 requested changes
Die tests sollten doch lieber in den tests folder - nicht in den src folder

2024-03-18 11:22 UTC, tilwbr commented
habs geändert :)

2024-03-18 13:35 UTC, CodeRider101 approved these changes

2024-03-18 14:25 UTC, CodeRider101 approved these changes

2024-03-19 07:20 UTC, merged