143 schüler daten ansicht backend
SE-TINF22B2/G2-Schoolify pull request #224
Opened 2024-03-22 10:26 UTC by tilwbr

### Beschreibung der Änderungen
- added get request to get student with its grades and tests and suvjects

### Issue
- #143 

### Checklist

- [x] Ich habe meinen code selber überprüft
- [x] Das Projekt kann ohne Probleme gestartet werden
- [x] Ich habe Tests geschrieben, falls das Issue ein Core Feature ist.
- [x] Ich habe meine Funktionen für die Verständlichkeit anderer mit Kommentaren ausgestattet
- [x] Ich habe den code gelinted (´npm run lint´)

2024-03-23 11:01 UTC, Kronprinz03 commented on serverside/package.json
What is this ?

2024-03-25 15:32 UTC, tilwbr commented on serverside/package.json
scheint so als wäre da nix verändert worden, keine ahnung wieso das im pr ist

2024-03-26 13:17 UTC, Kronprinz03 requested changes

2024-03-26 13:17 UTC, Kronprinz03 commented on serverside/src/student/student.controller.ts
Äh das frontend hat wahrscheinlich keinen zugriff auf die IDs die in der Datenbank verwendet werden wäre es nicht besser dafür dann die E-Mail zu benutzten ?

2024-04-02 16:56 UTC, Kronprinz03 submitted a review, later dismissed

2024-04-03 13:34 UTC, Kronprinz03 approved these changes
Lgtm

2024-04-03 13:43 UTC, merged