152 log in backend
SE-TINF22B2/G2-Schoolify pull request #227
Opened 2024-03-28 15:56 UTC by CodeRider101

### Beschreibung der Änderungen

### Issue

### Checklist

- [x] Ich habe meinen code selber überprüft
- [x] Das Projekt kann ohne Probleme gestartet werden
- [x] Ich habe Tests geschrieben, falls das Issue ein Core Feature ist.
- [x] Ich habe meine Funktionen für die Verständlichkeit anderer mit Kommentaren ausgestattet
- [x] Ich habe den code gelinted (´npm run lint´)

2024-03-28 16:47 UTC, Kronprinz03 commented
Kurze frage hast du daran gedacht die PR auf squashen einzustellen ?

2024-03-28 16:56 UTC, Kronprinz03 requested changes

2024-03-28 16:56 UTC, Kronprinz03 commented on serverside/src/auth/auth.service.ts
Glaube du brauchst nicht zu unterscheiden ob die E-Mail oder das Passwort falsch ist. Macht es am ende für Frontend besser.

2024-03-29 12:08 UTC, CodeRider101 commented on serverside/src/auth/auth.service.ts
1. squash and merge mach ich am schluss beim mergen
2. Find die Unterscheidung schon sinnvoll. Macht ja keinen sooo großen Unterschied. Einfach die Fehlermeldung anzeigen die man zurückbekommt

2024-03-29 15:09 UTC, Kronprinz03 commented on serverside/src/auth/auth.service.ts
Es macht es für das Front End schwerer da diese 2 Fehler Meldungen bekommen und es ist von der Security unseres Backend auch nicht wirklich gut

2024-03-29 16:36 UTC, CodeRider101 commented on serverside/src/auth/auth.service.ts
Was hat die Security denn nachteiig davon?

2024-04-02 14:17 UTC, Kronprinz03 commented on serverside/src/auth/auth.service.ts
googlen?

2024-04-02 14:21 UTC, merged