308 se readme für backend erstellen
SE-TINF22B2/G2-Schoolify pull request #309
Opened 2024-05-23 07:56 UTC by tilwbr

### Beschreibung der Änderungen
- README Anforderung von SE fürs Backend erstellt
### Issue
- #308 
### Checklist

- [x] Ich habe meinen code selber überprüft
- [x] Das Projekt kann ohne Probleme gestartet werden
- [ ] Ich habe Tests geschrieben, falls das Issue ein Core Feature ist.
- [ ] Ich habe meine Funktionen für die Verständlichkeit anderer mit Kommentaren ausgestattet
- [ ] Ich habe den code gelinted (´npm run lint´)

2024-05-23 08:08 UTC, two-Gee requested changes

2024-05-23 08:08 UTC, two-Gee commented on serverside/README.md
> +Alle anderen Ordner sind für die Entwicklung im Backend erstmal irrelevant und sollten nicht angefasst werden.
vielleicht trotzdem noch kurz prisma ordner erklären?

2024-05-23 08:08 UTC, two-Gee commented on serverside/README.md
> +### Ordnerstruktur
Ordnerstruktur als Überthema nehmen

2024-05-23 08:08 UTC, two-Gee commented on serverside/README.md
> +Unser Backend wird, wie in unserer Wiki im Teil der Technologien erklärt, mit NestJS entwickelt. Dabei verwenden wir einige Funktionen und Methodiken, die hier genauer erklärt werden. Die Schritte un
würde das zur Installation hier direkt reinschreiben, weil es sich nur auf die Entwicklung des Backends bezieht

2024-05-28 16:19 UTC, two-Gee requested changes

2024-05-28 16:19 UTC, two-Gee commented on serverside/README.md
> +## Ordnerstruktur
So wie es jetzt ist  gehört Backend Development zur Orderstruktur das passt noch nicht. 
Würde nur die Punkte Source Code, Tests, DTO und Prisma zur Orderstruktur packen

2024-05-28 20:10 UTC, tilwbr commented on serverside/README.md
> +## Ordnerstruktur
und wo würdest du backend development hinpacken?

2024-05-29 06:42 UTC, two-Gee approved these changes

2024-05-29 06:43 UTC, merged